CREATE DATABASE MEMBERSHIPBOARD;

CREATE TABLE USER(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    ADDRESS VARCHAR(100) NOT NULL,
    ROLE VARCHAR(10) NOT NULL
)ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE BOARD(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CONTENT VARCHAR(20) NOT NULL,
    TITLE LONGTEXT,
    READCOUNT INT DEFAULT 0,
    CREATEDATE TIMESTAMP,
    USER_ID INT,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
)ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;

CREATE TABLE REPLY(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    BOARD_ID INT,
    CONTENT VARCHAR(300) NOT NULL,
    CREATEDATE TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE SET NULL,
    FOREIGN KEY (BOARD_ID)REFERENCES BOARD(ID) ON DELETE CASCADE
)ENGINE=INNODB DEFAULT CHARACTER SET=UTF8;